### PR TITLE
IM DUMB SORRY

### PR DESCRIPTION
**Pull request by Kiffolisk**
SORRY LOL

### CODE REVIEW

**Comment by Texzx** [comment]
It's fine, except now the fixed PlayState.hx pops up with OptionsMenu.hx line 128, 7-11, missing something again. I'm way too tired to stare at code for another hour, but those are the only two Issues I'm having at this very moment in way of compiling.

**Comment by Kiffolisk** [comment]
ctrl.isMenuItem = true; 
this is the error line.
i might have forgotten to add like a semicolon or whatever

**Comment by Kiffolisk** [comment]
yep i did, fixed all the errors n shit

**Comment by Kiffolisk** [comment]
the fuck why did it close

**Pull request merged**
